services:
  mc:
    image: itzg/minecraft-server:java21          # Java 21 is required for MC 1.21.x :contentReference[oaicite:0]{index=0}
    container_name: minecraft-bettermc
    restart: on-failure:5
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"

    # -------- persistent data --------
    volumes:
      - ./data:/data
      #- ./BMC4_Server_Pack_v45.5:/data

    # -------- server settings --------
    environment:
      EULA: "TRUE"

      # --- CurseForge pack ---
      TYPE: AUTO_CURSEFORGE                    # turns on the helper
      VERSION: "1.20.1"                        # lock MC version so future ATM10 updates don’t jump packs
      CF_PAGE_URL:  "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4/files/6789609"
#      CF_SLUG: better-mc-neoforge-bmc5
      #CF_FILE_ID: "6789611"                    # 4.0 release, MC 1.21.1 server-files zip :contentReference[oaicite:2]{index=2}
      #API key for CurseForge
      CF_API_KEY: "enter-key-here"                # keep the key in a .env file (avoid leaking it)

      # --- JVM / gameplay bits ---
      MEMORY: 6G
      USE_AIKAR_FLAGS: "true"
      #FORCE_GAMEMODE: "true"
      #OVERRIDE_SERVER_START: "false"
      #Admins:
      OPS: player1

