services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
    # path to config folder
      - ~/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
