version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr-book
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      # /local/path:/containerpath
      # config file location
      - /srv/readarr-books/config:/config
      # location of media
      - /mnt/raiddisk1/books:/books
      # where media gets downloaded to
      - /home/downloads/completed/audio:/downloads
    ports:
      - 8788:8787
    restart: unless-stopped

