version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      # /local/path:/containerpath
      # config file location
      - /srv/Radarr/config:/config
      # data location
      - /mnt:/mnt #optional
      # downloaded file location
      - /home/downloads:/downloads #optional
    ports:
      # port number
      - 7878:7878
    restart: unless-stopped
    # optional segment: used to limit radarr cpu usage to 10%
    # current version of radarr uses max amount of cpu due to bug, hacky fix
    deploy:
      resources:
        limits:
          cpus: '0.1'
