services:
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago

      # time kometa will run
      - KOMETA_TIME=03:00 #optional
      # force it to run instead of waiting for specified time
      - KOMETA_RUN=False #optional
      # force It to run but don't apply changes to plex
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
    volumes:
    # location of config file
      - ~/docker/kometa/config:/config
    restart: unless-stopped
