version: "2.1"
services:
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # location of config file, uses container location not local
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      # /local/path:/containerfile
      # location of config file
      - /srv/pmm/config:/config
      # location for files
      - /mnt:/mnt
    restart: unless-stopped


