version: "3.8"
services:
  MinecraftBasicServer:
    image: ich777/minecraftbasicserver
    container_name: MinecraftBasicServer
    ports:
      - "25565:25565"
      - "9011:8080"
    environment:
      RUNTIME_NAME: "basicjre"
      JAR_NAME: "server"
      GAME_V: "latest"
      GAME_PORT: "25565"
      XMX_SIZE: "1024"
      XMS_SIZE: "1024"
      ACCEPT_EULA: 'true'
      UID: "99"
      GID: "100"
    volumes:
      - "/srv/minecraft/serverdata:/serverdata/serverfiles"
    restart: unless-stopped
