services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      # path to config file
      - ~/docker/lidarr/config:/config
      # paths to media
      - /mnt:/mnt
      # path to downloaded files locat
      - /mnt/md1/nzbget/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
